/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#006977",
        "primary-dim": "#005c68",
        "primary-container": "#8be5f6",
        "primary-fixed": "#8be5f6",
        "primary-fixed-dim": "#7dd6e8",
        "on-primary": "#edfcff",
        "on-primary-container": "#00535e",
        "on-primary-fixed": "#003e47",
        "on-primary-fixed-variant": "#005d6a",
        "secondary": "#49636f",
        "secondary-dim": "#3d5762",
        "secondary-container": "#cbe7f5",
        "secondary-fixed": "#cbe7f5",
        "secondary-fixed-dim": "#bdd9e6",
        "on-secondary": "#f2faff",
        "on-secondary-container": "#3c5561",
        "on-secondary-fixed": "#29434e",
        "on-secondary-fixed-variant": "#455f6b",
        "tertiary": "#8a4f40",
        "tertiary-dim": "#7c4435",
        "tertiary-container": "#feb19e",
        "tertiary-fixed": "#feb19e",
        "tertiary-fixed-dim": "#eea491",
        "on-tertiary": "#fff7f6",
        "on-tertiary-container": "#633022",
        "on-tertiary-fixed": "#491c10",
        "on-tertiary-fixed-variant": "#6e382a",
        "error": "#a83836",
        "error-dim": "#67040d",
        "error-container": "#fa746f",
        "on-error": "#fff7f6",
        "on-error-container": "#6e0a12",
        "background": "#f8fafb",
        "on-background": "#2c3436",
        "surface": "#f8fafb",
        "surface-bright": "#f8fafb",
        "surface-dim": "#d4dbde",
        "surface-tint": "#006977",
        "surface-variant": "#dce4e6",
        "surface-container": "#eaeff0",
        "surface-container-low": "#f0f4f6",
        "surface-container-high": "#e3e9eb",
        "surface-container-highest": "#dce4e6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#2c3436",
        "on-surface-variant": "#596063",
        "outline": "#757c7e",
        "outline-variant": "#acb3b6",
        "inverse-surface": "#0b0f10",
        "inverse-on-surface": "#9a9d9e",
        "inverse-primary": "#8be5f6",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      fontFamily: {
        "manrope": ["Manrope", "sans-serif"],
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "mono": ["ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
    },
  },
  plugins: [forms],
};
